// Centralized building cost definitions for backend
// Keep values aligned with frontend `frontend/src/constants/buildings.js`
const BUILDING_COSTS = {
  house: { wood: 20, stone: 10, food: 5, popNeeded: 0 },
  // Special housing variants that increase specific population buckets
  casa_de_piedra: { lumber: 10, baked_brick: 5, popNeeded: 0 }, // increases burgess.max_population
  casa_de_ladrillos: { magic_catalyst: 4, linen: 3, popNeeded: 0 }, // increases patrician.max_population
  sawmill: { wood: 50, stone: 30, food: 10, popNeeded: 1 },
  quarry: { wood: 40, stone: 80, food: 15 },
  quarry: { wood: 40, stone: 80, food: 15, popNeeded: 1 },
  farm: { wood: 40, stone: 10, food: 0, popNeeded: 1 },
  well: { wood: 15, stone: 10, food: 0 },
  well: { wood: 15, stone: 10, food: 0, popNeeded: 1 },
  clay_pit: { wood: 20, stone: 20, food: 0, popNeeded: 1 },
  tannery: { wood: 25, stone: 15, food: 5 },
  tannery: { wood: 25, stone: 15, food: 5, popNeeded: 1 },
  coal_mine: { wood: 30, stone: 40, food: 0, popNeeded: 1 },
  copper_mine: { wood: 35, stone: 45, food: 0 },
  copper_mine: { wood: 35, stone: 45, food: 0, popNeeded: 1 },
  sheepfold: { wood: 20, stone: 10, food: 5, popNeeded: 1 },
  apiary: { wood: 15, stone: 5, food: 0 },
  apiary: { wood: 15, stone: 5, food: 0, popNeeded: 1 },
  sastreria: { wood: 60, stone: 20, food: 10, popNeeded: 1 },
  carpinteria: { wood: 40, stone: 20, food: 5 },
  carpinteria: { wood: 40, stone: 20, food: 5, popNeeded: 1 },
  fabrica_ladrillos: { wood: 30, stone: 25, food: 5, popNeeded: 1 },
  bazar_especias: { wood: 20, stone: 15, food: 10 },
  bazar_especias: { wood: 20, stone: 15, food: 10, popNeeded: 1 },
  alfareria: { wood: 25, stone: 20, food: 5, popNeeded: 1 },
  tintoreria_morada: { wood: 30, stone: 15, food: 5 },
  tintoreria_morada: { wood: 30, stone: 15, food: 5, popNeeded: 1 },
  herreria: { wood: 50, stone: 40, food: 10, popNeeded: 1 },
  salazoneria: { wood: 25, stone: 20, food: 5 },
  salazoneria: { wood: 25, stone: 20, food: 5, popNeeded: 1 },
  libreria: { wood: 45, stone: 10, food: 5, popNeeded: 1 },
  cerveceria: { wood: 30, stone: 10, food: 10 },
  cerveceria: { wood: 30, stone: 10, food: 10, popNeeded: 1 },
  forja: { wood: 40, stone: 30, food: 8, popNeeded: 1 },
  elixireria: { wood: 30, stone: 20, food: 10 },
  elixireria: { wood: 30, stone: 20, food: 10, popNeeded: 1 },
  tintoreria_real: { wood: 35, stone: 20, food: 10, popNeeded: 1 },
  escriba: { wood: 20, stone: 10, food: 5 },
  escriba: { wood: 20, stone: 10, food: 5, popNeeded: 1 },
  artificiero: { wood: 45, stone: 30, food: 15, popNeeded: 1 },
  herreria_real: { wood: 60, stone: 50, food: 15 },
  herreria_real: { wood: 60, stone: 50, food: 15, popNeeded: 1 },
  lineria: { wood: 30, stone: 20, food: 8, popNeeded: 1 },
  // Strategic buildings
  tintoreria_dorada: { wood: 60, stone: 40, food: 10, popNeeded: 1 },
  herreria_mitica: { wood: 80, stone: 120, food: 20, popNeeded: 2 },
  salinas: { wood: 30, stone: 20, food: 50, popNeeded: 1 },
  mina_azufre: { wood: 50, stone: 70, food: 10, popNeeded: 1 },
  mina_gemas: { wood: 90, stone: 150, food: 20, popNeeded: 2 },
  telar_real: { wood: 70, stone: 30, food: 15, popNeeded: 1 },
};

module.exports = { BUILDING_COSTS };
